namespace Loxifi.Structures
{
	internal enum EIEIFLAG
	{
		IEIFLAG_ASYNC = 1,
		IEIFLAG_CACHE = 2,
		IEIFLAG_ASPECT = 4,
		IEIFLAG_OFFLINE = 8,
		IEIFLAG_GLEAM = 16,
		IEIFLAG_SCREEN = 32,
		IEIFLAG_ORIGSIZE = 64,
		IEIFLAG_NOSTAMP = 128,
		IEIFLAG_NOBORDER = 256,
		IEIFLAG_QUALITY = 512
	}
}
